config/routes.rb
Rails.application.routes.draw do

  get 'stream/registrations' => 'stream#registrations'
  resources :stream

  resources :service_providers do
    member do
      get 'add_person'
    end
    resources :people, only: [:edit]
  end

  get 'session/login'
  post 'session/login' => 'session#do_login'
  get 'session/logout'

  resources :people, only: [:show, :create, :update, :new, :edit]

  root :to => 'welcome#index'
  get 'checklist' => 'welcome#checklist'

end

app/models/person.rb
class Person
    include MongoMapper::Document

    include PublicActivity::Model
    tracked

    timestamps!

    def new(args)
      args.each do |key, value|
        self[key] = value
      end
    end

    #todo re-think about this, in context of variable attributes
  def v_card
    <<-eos
BEGIN:VCARD
VERSION:2.1
N:#{self[:last_name]};#{self[:first_name]}
UID:urn:uuid:#{self[:_id]}
TEL;HOME;voice:#{self[:current_contact_phone]}
ADR:;;#{self[:address]};#{self[:suburb]};#{self[:state]};#{self[:postcode]}
EMAIL:#{self[:email]}
END:VCARD
    eos
  end

  def name
    "#{self[:first_name]} #{self[:last_name]}"
  end
end

app/models/qr_code/link.rb
module QrCode
  class Link
    def content(person)
      Rails.application.routes.url_helpers.person_url(person)
    end
  end
end

app/models/qr_code/vcard.rb
module QrCode
  class Vcard
    def content(person)
      person.v_card
    end
  end
end

app/models/service_provider.rb
class ServiceProvider
    include MongoMapper::Document
    extend Enumerize


    key :name, String

    key :clients, Array
    many :person, :in => :clients

    one :wizard, class: Wizard::Wizard
    one :workbench, class: Workbench::Workbench

    key :special_role
    enumerize :special_role, in: [:registration], scope: true
   


    timestamps!

end

app/models/wizard/buttons.rb
module Wizard
  class Buttons < Component
    many :content, class: Component
  end
end

app/models/wizard/dropdown.rb
module Wizard
  class Dropdown < Component
    key :attribute, String
    key :label, String
    key :placeholder, String
    key :options, Array
  end
end

app/models/wizard/headline.rb
module Wizard
  class Headline < Component
    key :text, String
  end
end

app/models/wizard/input.rb
module Wizard
  class Input < Component
    key :attribute, String
    key :label, String
    key :placeholder, String
    key :type, String
    key :additional_container_class, String

    def initialize(params)
      super
      @type = 'text' unless @type
    end
  end
end

app/models/wizard/link.rb
module Wizard
  class Link < Component
    key :target, String
    key :label, String
  end
end

app/models/wizard/qr.rb
module Wizard
  class Qr < Component
  end
end

app/models/wizard/split.rb
module Wizard
  class Split < Component
    many :content, class: Component

    @@map = {1 => 'one', 2 => 'two', 3 => 'three'}

    def number
      @@map[content.length]
    end
  end
end

app/models/wizard/wizard.rb
module Wizard
  class Wizard < Component
    many :content, class: Wizard::WizardNode
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def settings
    Rails.application.config
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :update, :edit]
  before_action :set_service_provider, only: [:edit, :update]

  def show
    respond_to do |format|
      format.png do
          qr_code = Services::Token.qr_code(@person, 8).to_img.resize(400, 400)
          send_data qr_code, :type => 'image/png', :disposition => 'inline'
      end
      format.vcf {
        @person.create_activity :vcard_accessed
        render plain: @person.v_card.to_s
        response.content_type = "text/x-vcard"
        response.headers['Content-Length'] = @person.v_card.size.to_s
      }
      format.pdf {
          pdf = Services::Token.generate_token_pdf(@person, settings.token_media)
          send_data pdf.render, filename: "token-#{@person.id}.pdf", type: 'application/pdf'
      }
      format.json { render :json => @person }
    end
  end

  def create
    @person = Person.new(person_params)
    respond_to do |format|
      if @person.save
        format.json { render :show, status: :created, location: @person }
      else
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @wizard = @service_provider.wizard
  end

  def update
    @service_provider.person.push(@person)
    @service_provider.save
    respond_to do |format|
      if @person.update_attributes(person_params)
        format.json { render :show, status: :ok, location: @person }
      else
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @wizard = ServiceProvider.find_by_special_role(:registration).wizard
  end

  private
    def set_person
      @person = Person.find(params[:id])
    end

    def set_service_provider
      @service_provider = ServiceProvider.find(params[:service_provider_id])
    end

    def person_params
      params.require(:person).except!(:uuid, :created_at, :updated_at).permit!
    end
end

app/controllers/service_providers_controller.rb
class ServiceProvidersController < ApplicationController
  before_action :set_service_provider, only: [:show, :edit, :update, :destroy, :add_person]

  # GET /service_providers
  # GET /service_providers.json
  def index
    @service_providers = ServiceProvider.all
  end

  # GET /service_providers/1
  # GET /service_providers/1.json
  def show
    @workbench = @service_provider.workbench
    respond_to do |format|
      format.html  { render  }
      format.csv  { render csv: @service_provider.person, only: ['_id'] + @workbench.table_attributes.keys  }
    end
  end

  # GET /service_providers/new
  def new
    @service_provider = ServiceProvider.new
  end

  # GET /service_providers/1/edit
  def edit
  end

  # POST /service_providers
  # POST /service_providers.json
  def create
    @service_provider = ServiceProvider.new(service_provider_params)
    respond_to do |format|
      if @service_provider.save
        format.html { redirect_to @service_provider, notice: 'Service provider was successfully created.' }
        format.json { render :show, status: :created, location: @service_provider }
      else
        format.html { render :new }
        format.json { render json: @service_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_providers/1
  # PATCH/PUT /service_providers/1.json
  def update
    respond_to do |format|
      if @service_provider.update_attributes(service_provider_params)
        format.html { redirect_to @service_provider, notice: 'Service provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_provider }
      else
        format.html { render :edit }
        format.json { render json: @service_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_providers/1
  # DELETE /service_providers/1.json
  def destroy
    @service_provider.destroy
    respond_to do |format|
      format.html { redirect_to service_providers_url, notice: 'Service provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_service_provider
      @service_provider = ServiceProvider.find(params[:id])
      logger.debug "From mongo #{@service_provider.to_mongo}"
    end

    def service_provider_params
      params.require(:service_provider).permit(:name)
    end
end

app/controllers/stream_controller.rb
class StreamController < ApplicationController
  def index
    @activities = PublicActivity::Activity.all
    render action: :index
  end

  def registrations
    @people = Person.where(:created_at.gt => Time.parse(params[:since]))

    respond_to do |format|
      format.json { render json: @people }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/service_providers_helper.rb
module ServiceProvidersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wizard_helper.rb
module WizardHelper
end

app/views/people/edit.html.erb
<%= @service_provider[:name] %> :
<%= @person.name %>

<%= render 'wizard/wizard', wizard: @wizard %>

app/views/people/new.html.erb
<%= render 'wizard/wizard', wizard: @wizard %>

app/views/public_activity/person/_create.html.erb
<div class="event">
  <div class="label">
    <i class="circular add sign icon"></i>
  </div>

  <div class="content">
    <div class="date">
      <%= distance_of_time_in_words_to_now(a.created_at) %> ago
    </div>

    <div class="summary">
      <%= link_to a.trackable.name, a.trackable %> registered
    </div>
  </div>
</div>

app/views/public_activity/person/_vcard_accessed.html.erb
<div class="event">
  <div class="label">
    <i class="circular qr code icon"></i>
  </div>

  <div class="content">
    <div class="date">
      <%= distance_of_time_in_words_to_now(a.created_at) %> ago
    </div>

    <div class="summary">
      <%= link_to a.trackable.name, a.trackable %>'s v-card has been scanned
    </div>
  </div>
</div>

app/views/service_providers/_form.html.erb
<%= form_for(@service_provider) do |f| %>
<div class="ui error form segment">
  <div class="ui blue segment">

    <% if @service_provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service_provider.errors.count, "error") %> prohibited this service_provider from being saved:</h2>

      <ul>
        <% @service_provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
  </div>

    <div class="actions">
      <%= f.submit %>
    </div>
</div>
<% end %>

app/views/service_providers/add_person.html.erb
test

app/views/service_providers/edit.html.erb
<h1>Editing Service Provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_provider %> |
<%= link_to 'Back', service_providers_path %>

app/views/service_providers/index.html.erb
<h1>Listing Service Providers</h1>

<table class="ui table segment">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @service_providers.each do |service_provider| %>
      <tr>
        <td><%= link_to service_provider.name, service_provider %></td>
        <td>
        <%= link_to 'Edit', edit_service_provider_path(service_provider) %> |
        <%= link_to 'Destroy', service_provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service provider', new_service_provider_path %>

app/views/service_providers/new.html.erb
<h1>New Service Provider</h1>

<%= render 'form' %>

<%= link_to 'Back', service_providers_path %>

app/views/service_providers/show.html.erb
<p id="notice"><%= notice %></p>

<div class="details"><%= @service_provider.name %></div>

<div>
  <div class="ui huge inverted center aligned icon header"><%= image_tag("firststop_logo_sml.png", alt:"") %></div>
  <div class="ui huge red center aligned icon header">Align the QR code to scan.</div>
  <div id="qr_scanner" class="ui huge inverted center aligned icon header" 
      data-enabled="true" 
      data-action="<%= service_provider_path(@service_provider)%>/people/{{uuid}}/edit">
    <video id="video" style="height:200px;" autoplay></video>
    <canvas id="qr-canvas" width="800" height="600" style="display:none;width:800px;height:600px;"></canvas>
  </div>
  <div id="wait" class="ui huge inverted center aligned icon header" data-enabled="true">
    <input type="text" value="0" class="dial"
      data-fgColor="#0971CE"
      data-displayInput="false"
      data-step="1"
      data-min="0"
      data-max="1000">
  </div>
</div>

<div>
  <table class="ui table segment sortable">
    <thead>
      <tr>
        <% @workbench.table_attributes.each do |attribute, label| %>
          <th><%= label %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @service_provider.person.each do |person| %>
        <tr class="<%= person[:status] %>">
          <% @workbench.table_attributes.each do |attribute, label| %>
            <% if attribute == @workbench.status_attribute %>
              <td class="<%= @workbench.statuses[person[attribute]].try(:[], 'css_class') %>"><%= @workbench.statuses[person[attribute]].try(:[], 'label') %></td>
            <% else %>
              <td><%= person[attribute] %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>

    <tfoot>
      <tr>
        <th colspan="<%= @workbench.table_attributes.size %>"><%= @service_provider.clients.size %> clients total</th>
      </tr>
    </tfoot>
  </table>

</div>


<script>
$(function() {
  $(".dial").hide();

  $(".dial").bind('go', function() {
    $(".dial").knob();
    $({value: 0})
    .animate({value: 1000}, {
      duration: 500, easing: "swing",
      step: function() {
        $(".dial").val(Math.ceil(this.value)).trigger("change");
      }
    })
  })
});
</script>